[package]
name = "ferrotoken"
version = "0.1.0"
authors = ["Ted Monchamp <ted.monchamp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.2.1"
image = "0.23.12"
