[package]
name = "ferrotoken"
version = "0.1.0"
authors = ["Ted Monchamp"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.2.1"
clap = "2.33.0"
hex = "0.4.2"
image = "0.23.12"
regex = "1.4.3"
